# this dockerfile is used for product deployments
FROM python:3.7-alpine
LABEL maintainer "Federico Marani <me@federicomarani.com>"

RUN apk update && \
    apk add --virtual build-deps gcc musl-dev && \
    apk add postgresql-dev && \
    rm -rf /var/cache/apk/*

COPY requirements.txt requirements.txt
COPY requirements-dev.txt requirements-dev.txt

RUN pip install -r requirements.txt -r requirements-dev.txt

RUN apk del build-deps gcc musl-dev

COPY . /app
WORKDIR /app

EXPOSE 5000
