version: '3.1'

services:

  postgres:
    restart: always
    image: postgres:11-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432

  web:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    environment:
      - FLASK_ENV=docker
    command: ./wait-for.sh postgres:5432 -- ./docker_entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: "local"
